theme: jekyll-theme-minimal
title: Sistemas Multimídia (2019.1)
email: etorresini@ifsc.edu.br
description: >
  Este é um projeto em desenvolvimento na disciplina de Sistemas Multimídia
  do Curso de Engenharia de Telecomunicações do IFSC câmpus São José -
  primeiro semestre de 2019.
baseurl: ''
url: 'https://boidacarapreta.github.io/smu20191'
github_username: boidacarapreta
#sass:
#  sass_dir: _sass
include: ['_pages']
